### ISSUE TITLE
BOM?

### ISSUE THREAD

**Issue by jayjlow** [bikerglen/pixpoe#1]
Sorry if I missed it in your blog, but is there a handy BOM available?

**Comment by bikerglen** [comment]
I'll upload it tonight after work. It's in the form of an Excel spreadsheet with Manufacturer and Digi-Key part numbers.

**Comment by jayjlow** [comment]
Awe yeah. Thanks for responding so quickly. Have a great new years.

**Comment by bikerglen** [comment]
BOM added to boards/v2 directory.
