### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hpux735** [bikerglen/pixpoe#2]
Hi!

This project is awesome!

Under what license are you releasing this work?  I don't see it in the readme, blog post, or silkscreen.

Thanks!

**Comment by bikerglen** [comment]
Thanks! Would GNU GPL V3.0 or higher work for your application? If so, GNU GPL V3.0 or higher. If not, let me know what you need and I'll go do some research.

**Comment by hpux735** [comment]
Yah, I think that GPL v. 3 is probably OK.  Thanks again.
